# Generated by Django 3.0.8 on 2020-07-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.CharField(choices=[('Fishing Rod', 'fishing_rod.png'), ('Fishing Net', 'fishing_net.png'), ('Tackle Box', 'tackle_box.png'), ('Lure', 'lure.png'), ('Line', 'line.png'), ('Hook', 'hook.png')], default='Fishing Rod', max_length=25),
        ),
    ]
