# Generated by Django 3.0.4 on 2020-06-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_post_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=1),
        ),
    ]
