# Generated by Django 3.0.4 on 2020-06-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0003_auto_20200615_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=1),
        ),
    ]
