# Generated by Django 3.0.4 on 2020-06-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0004_auto_20200615_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ticket_type',
            field=models.CharField(choices=[('Features', 'Feature Request'), ('Bug/Error', 'Bug/Error'), ('OtherComments', 'Other Comments')], default='Features', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.IntegerField(choices=[(3, 'Low'), (2, 'Normal'), (1, 'High')], default=1),
        ),
    ]
