# Generated by Django 3.0.4 on 2020-06-16 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0005_auto_20200615_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='assigned_developer',
            field=models.CharField(choices=[('david', ''), ('DerekJeter', ''), ('John', ''), ('Derek', ''), ('davidgm', ''), ('dfsdf', ''), ('yes', '')], default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=50),
        ),
    ]
