# Generated by Django 3.0.4 on 2020-06-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0006_post_assigned_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='assigned_developer',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('InProgress', 'In Progress'), ('AddInfo', 'Additional Info Required')], default='Open', max_length=25),
        ),
    ]
