# Generated by Django 3.0.4 on 2020-06-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0007_auto_20200615_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('InProgress', 'In Progress'), ('AddInfo', 'Additional Info Required'), ('Completed', 'Completed')], default='Open', max_length=25),
        ),
    ]
