# Generated by Django 3.0.4 on 2020-06-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0008_auto_20200615_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ticket_type',
            field=models.CharField(choices=[('Features', 'Feature Request'), ('Bug/Error', 'Bug/Error'), ('Design', 'Design')], default='Features', max_length=25),
        ),
    ]
