# Generated by Django 3.0.4 on 2020-06-18 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0015_auto_20200617_1904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='MyProjects',
        ),
    ]
