# Generated by Django 3.0.4 on 2020-06-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0018_auto_20200619_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprojects',
            name='project_manager',
        ),
    ]
