# Generated by Django 3.0.4 on 2020-06-19 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker', '0021_auto_20200619_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='assigned_developer',
        ),
        migrations.AddField(
            model_name='myprojects',
            name='project_manager',
            field=models.ForeignKey(default='Admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
