# Generated by Django 3.0.4 on 2020-06-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0022_auto_20200619_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprojects',
            name='project_manager',
        ),
    ]
